# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aaron/QGIS_Plugins_dev/hydra2dgpu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aaron/QGIS_Plugins_dev/hydra2dgpu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/QGIS_Plugins_dev/hydra2dgpu/CMakeFiles /home/aaron/QGIS_Plugins_dev/hydra2dgpu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/QGIS_Plugins_dev/hydra2dgpu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hydra_swe2d

# Build rule for target.
hydra_swe2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hydra_swe2d
.PHONY : hydra_swe2d

# fast build rule for target.
hydra_swe2d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/build
.PHONY : hydra_swe2d/fast

#=============================================================================
# Target rules for targets named hydra_hybridmesh

# Build rule for target.
hydra_hybridmesh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hydra_hybridmesh
.PHONY : hydra_hybridmesh

# fast build rule for target.
hydra_hybridmesh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_hybridmesh.dir/build.make CMakeFiles/hydra_hybridmesh.dir/build
.PHONY : hydra_hybridmesh/fast

#=============================================================================
# Target rules for targets named hydra_meshing_native

# Build rule for target.
hydra_meshing_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hydra_meshing_native
.PHONY : hydra_meshing_native

# fast build rule for target.
hydra_meshing_native/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_meshing_native.dir/build.make CMakeFiles/hydra_meshing_native.dir/build
.PHONY : hydra_meshing_native/fast

#=============================================================================
# Target rules for targets named hydra_overlay

# Build rule for target.
hydra_overlay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hydra_overlay
.PHONY : hydra_overlay

# fast build rule for target.
hydra_overlay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_overlay.dir/build.make CMakeFiles/hydra_overlay.dir/build
.PHONY : hydra_overlay/fast

cpp/src/hybrid_mesh_bindings.o: cpp/src/hybrid_mesh_bindings.cpp.o
.PHONY : cpp/src/hybrid_mesh_bindings.o

# target to build an object file
cpp/src/hybrid_mesh_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_hybridmesh.dir/build.make CMakeFiles/hydra_hybridmesh.dir/cpp/src/hybrid_mesh_bindings.cpp.o
.PHONY : cpp/src/hybrid_mesh_bindings.cpp.o

cpp/src/hybrid_mesh_bindings.i: cpp/src/hybrid_mesh_bindings.cpp.i
.PHONY : cpp/src/hybrid_mesh_bindings.i

# target to preprocess a source file
cpp/src/hybrid_mesh_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_hybridmesh.dir/build.make CMakeFiles/hydra_hybridmesh.dir/cpp/src/hybrid_mesh_bindings.cpp.i
.PHONY : cpp/src/hybrid_mesh_bindings.cpp.i

cpp/src/hybrid_mesh_bindings.s: cpp/src/hybrid_mesh_bindings.cpp.s
.PHONY : cpp/src/hybrid_mesh_bindings.s

# target to generate assembly for a file
cpp/src/hybrid_mesh_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_hybridmesh.dir/build.make CMakeFiles/hydra_hybridmesh.dir/cpp/src/hybrid_mesh_bindings.cpp.s
.PHONY : cpp/src/hybrid_mesh_bindings.cpp.s

cpp/src/meshing_native_bindings.o: cpp/src/meshing_native_bindings.cpp.o
.PHONY : cpp/src/meshing_native_bindings.o

# target to build an object file
cpp/src/meshing_native_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_meshing_native.dir/build.make CMakeFiles/hydra_meshing_native.dir/cpp/src/meshing_native_bindings.cpp.o
.PHONY : cpp/src/meshing_native_bindings.cpp.o

cpp/src/meshing_native_bindings.i: cpp/src/meshing_native_bindings.cpp.i
.PHONY : cpp/src/meshing_native_bindings.i

# target to preprocess a source file
cpp/src/meshing_native_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_meshing_native.dir/build.make CMakeFiles/hydra_meshing_native.dir/cpp/src/meshing_native_bindings.cpp.i
.PHONY : cpp/src/meshing_native_bindings.cpp.i

cpp/src/meshing_native_bindings.s: cpp/src/meshing_native_bindings.cpp.s
.PHONY : cpp/src/meshing_native_bindings.s

# target to generate assembly for a file
cpp/src/meshing_native_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_meshing_native.dir/build.make CMakeFiles/hydra_meshing_native.dir/cpp/src/meshing_native_bindings.cpp.s
.PHONY : cpp/src/meshing_native_bindings.cpp.s

cpp/src/overlay_backend.o: cpp/src/overlay_backend.cpp.o
.PHONY : cpp/src/overlay_backend.o

# target to build an object file
cpp/src/overlay_backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_overlay.dir/build.make CMakeFiles/hydra_overlay.dir/cpp/src/overlay_backend.cpp.o
.PHONY : cpp/src/overlay_backend.cpp.o

cpp/src/overlay_backend.i: cpp/src/overlay_backend.cpp.i
.PHONY : cpp/src/overlay_backend.i

# target to preprocess a source file
cpp/src/overlay_backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_overlay.dir/build.make CMakeFiles/hydra_overlay.dir/cpp/src/overlay_backend.cpp.i
.PHONY : cpp/src/overlay_backend.cpp.i

cpp/src/overlay_backend.s: cpp/src/overlay_backend.cpp.s
.PHONY : cpp/src/overlay_backend.s

# target to generate assembly for a file
cpp/src/overlay_backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_overlay.dir/build.make CMakeFiles/hydra_overlay.dir/cpp/src/overlay_backend.cpp.s
.PHONY : cpp/src/overlay_backend.cpp.s

cpp/src/swe2d_bindings.o: cpp/src/swe2d_bindings.cpp.o
.PHONY : cpp/src/swe2d_bindings.o

# target to build an object file
cpp/src/swe2d_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_bindings.cpp.o
.PHONY : cpp/src/swe2d_bindings.cpp.o

cpp/src/swe2d_bindings.i: cpp/src/swe2d_bindings.cpp.i
.PHONY : cpp/src/swe2d_bindings.i

# target to preprocess a source file
cpp/src/swe2d_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_bindings.cpp.i
.PHONY : cpp/src/swe2d_bindings.cpp.i

cpp/src/swe2d_bindings.s: cpp/src/swe2d_bindings.cpp.s
.PHONY : cpp/src/swe2d_bindings.s

# target to generate assembly for a file
cpp/src/swe2d_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_bindings.cpp.s
.PHONY : cpp/src/swe2d_bindings.cpp.s

cpp/src/swe2d_gpu.o: cpp/src/swe2d_gpu.cu.o
.PHONY : cpp/src/swe2d_gpu.o

# target to build an object file
cpp/src/swe2d_gpu.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_gpu.cu.o
.PHONY : cpp/src/swe2d_gpu.cu.o

cpp/src/swe2d_gpu.i: cpp/src/swe2d_gpu.cu.i
.PHONY : cpp/src/swe2d_gpu.i

# target to preprocess a source file
cpp/src/swe2d_gpu.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_gpu.cu.i
.PHONY : cpp/src/swe2d_gpu.cu.i

cpp/src/swe2d_gpu.s: cpp/src/swe2d_gpu.cu.s
.PHONY : cpp/src/swe2d_gpu.s

# target to generate assembly for a file
cpp/src/swe2d_gpu.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_gpu.cu.s
.PHONY : cpp/src/swe2d_gpu.cu.s

cpp/src/swe2d_gpu_redistribute.o: cpp/src/swe2d_gpu_redistribute.cu.o
.PHONY : cpp/src/swe2d_gpu_redistribute.o

# target to build an object file
cpp/src/swe2d_gpu_redistribute.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_gpu_redistribute.cu.o
.PHONY : cpp/src/swe2d_gpu_redistribute.cu.o

cpp/src/swe2d_gpu_redistribute.i: cpp/src/swe2d_gpu_redistribute.cu.i
.PHONY : cpp/src/swe2d_gpu_redistribute.i

# target to preprocess a source file
cpp/src/swe2d_gpu_redistribute.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_gpu_redistribute.cu.i
.PHONY : cpp/src/swe2d_gpu_redistribute.cu.i

cpp/src/swe2d_gpu_redistribute.s: cpp/src/swe2d_gpu_redistribute.cu.s
.PHONY : cpp/src/swe2d_gpu_redistribute.s

# target to generate assembly for a file
cpp/src/swe2d_gpu_redistribute.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_gpu_redistribute.cu.s
.PHONY : cpp/src/swe2d_gpu_redistribute.cu.s

cpp/src/swe2d_mesh.o: cpp/src/swe2d_mesh.cpp.o
.PHONY : cpp/src/swe2d_mesh.o

# target to build an object file
cpp/src/swe2d_mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_mesh.cpp.o
.PHONY : cpp/src/swe2d_mesh.cpp.o

cpp/src/swe2d_mesh.i: cpp/src/swe2d_mesh.cpp.i
.PHONY : cpp/src/swe2d_mesh.i

# target to preprocess a source file
cpp/src/swe2d_mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_mesh.cpp.i
.PHONY : cpp/src/swe2d_mesh.cpp.i

cpp/src/swe2d_mesh.s: cpp/src/swe2d_mesh.cpp.s
.PHONY : cpp/src/swe2d_mesh.s

# target to generate assembly for a file
cpp/src/swe2d_mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_mesh.cpp.s
.PHONY : cpp/src/swe2d_mesh.cpp.s

cpp/src/swe2d_numerics.o: cpp/src/swe2d_numerics.cpp.o
.PHONY : cpp/src/swe2d_numerics.o

# target to build an object file
cpp/src/swe2d_numerics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_numerics.cpp.o
.PHONY : cpp/src/swe2d_numerics.cpp.o

cpp/src/swe2d_numerics.i: cpp/src/swe2d_numerics.cpp.i
.PHONY : cpp/src/swe2d_numerics.i

# target to preprocess a source file
cpp/src/swe2d_numerics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_numerics.cpp.i
.PHONY : cpp/src/swe2d_numerics.cpp.i

cpp/src/swe2d_numerics.s: cpp/src/swe2d_numerics.cpp.s
.PHONY : cpp/src/swe2d_numerics.s

# target to generate assembly for a file
cpp/src/swe2d_numerics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_numerics.cpp.s
.PHONY : cpp/src/swe2d_numerics.cpp.s

cpp/src/swe2d_solver.o: cpp/src/swe2d_solver.cpp.o
.PHONY : cpp/src/swe2d_solver.o

# target to build an object file
cpp/src/swe2d_solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_solver.cpp.o
.PHONY : cpp/src/swe2d_solver.cpp.o

cpp/src/swe2d_solver.i: cpp/src/swe2d_solver.cpp.i
.PHONY : cpp/src/swe2d_solver.i

# target to preprocess a source file
cpp/src/swe2d_solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_solver.cpp.i
.PHONY : cpp/src/swe2d_solver.cpp.i

cpp/src/swe2d_solver.s: cpp/src/swe2d_solver.cpp.s
.PHONY : cpp/src/swe2d_solver.s

# target to generate assembly for a file
cpp/src/swe2d_solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_swe2d.dir/build.make CMakeFiles/hydra_swe2d.dir/cpp/src/swe2d_solver.cpp.s
.PHONY : cpp/src/swe2d_solver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hydra_hybridmesh"
	@echo "... hydra_meshing_native"
	@echo "... hydra_overlay"
	@echo "... hydra_swe2d"
	@echo "... cpp/src/hybrid_mesh_bindings.o"
	@echo "... cpp/src/hybrid_mesh_bindings.i"
	@echo "... cpp/src/hybrid_mesh_bindings.s"
	@echo "... cpp/src/meshing_native_bindings.o"
	@echo "... cpp/src/meshing_native_bindings.i"
	@echo "... cpp/src/meshing_native_bindings.s"
	@echo "... cpp/src/overlay_backend.o"
	@echo "... cpp/src/overlay_backend.i"
	@echo "... cpp/src/overlay_backend.s"
	@echo "... cpp/src/swe2d_bindings.o"
	@echo "... cpp/src/swe2d_bindings.i"
	@echo "... cpp/src/swe2d_bindings.s"
	@echo "... cpp/src/swe2d_gpu.o"
	@echo "... cpp/src/swe2d_gpu.i"
	@echo "... cpp/src/swe2d_gpu.s"
	@echo "... cpp/src/swe2d_gpu_redistribute.o"
	@echo "... cpp/src/swe2d_gpu_redistribute.i"
	@echo "... cpp/src/swe2d_gpu_redistribute.s"
	@echo "... cpp/src/swe2d_mesh.o"
	@echo "... cpp/src/swe2d_mesh.i"
	@echo "... cpp/src/swe2d_mesh.s"
	@echo "... cpp/src/swe2d_numerics.o"
	@echo "... cpp/src/swe2d_numerics.i"
	@echo "... cpp/src/swe2d_numerics.s"
	@echo "... cpp/src/swe2d_solver.o"
	@echo "... cpp/src/swe2d_solver.i"
	@echo "... cpp/src/swe2d_solver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

