"""In-dock documentation hub — cross-document search and viewer for the CFD Inspector.

Shows an index of all available guides.  Search queries span every indexed
document simultaneously and display results grouped by source document.
Click any doc or search result to open the full document with a "Home"
button to return to the index.

Usage
-----
    from swe2d.workbench.doc_viewer import DocHubWidget

    hub = DocHubWidget(parent=self)
    inspector_tabs.addTab(hub, "Help")
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from qgis.PyQt.QtCore import Qt, QUrl
from qgis.PyQt.QtGui import QTextCursor
from qgis.PyQt.QtWidgets import (
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QPushButton,
    QStackedLayout,
    QTextBrowser,
    QVBoxLayout,
    QWidget,
)


# ── Document registry ────────────────────────────────────────────────────

@dataclass
class DocEntry:
    """A documentation source file."""
    title: str
    filename: str
    description: str = ""
    tags: List[str] = field(default_factory=list)


AVAILABLE_DOCS: List[DocEntry] = [
    DocEntry(
        title="User Guide",
        filename="USER_GUIDE.md",
        description="Complete user manual — installation, model setup, solver, post-processing & theory.",
        tags=["user", "setup", "solver", "results", "theory"],
    ),
    DocEntry(
        title="Gmsh Meshing Guide",
        filename="GMSH_MESHING_GUIDE.md",
        description="Gmsh backend reference — conceptual topology, cell types, quality controls, CLI.",
        tags=["mesh", "gmsh", "topology", "quality"],
    ),
    DocEntry(
        title="Developer Guide",
        filename="DEVELOPER_GUIDE.md",
        description="Code architecture, module reference, style guide, test suite, and Studio UI API.",
        tags=["developer", "api", "style", "tests"],
    ),
    DocEntry(
        title="C++ API Reference",
        filename="",  # Doxygen HTML — opened in external browser
        description="C++/CUDA native module API documentation (generated by Doxygen).",
        tags=["cpp", "cuda", "kernel", "native"],
    ),
    DocEntry(
        title="Studio GUI API",
        filename="STUDIO_GUI_API.md",
        description="Studio UI component registry, dock lifecycle, and host-window integration.",
        tags=["studio", "ui", "dock", "gui"],
    ),
    DocEntry(
        title="UI Component Guide",
        filename="UI_COMPONENT_GUIDE.md",
        description="Widget bindings, tab views, and event wiring patterns for the workbench.",
        tags=["ui", "widgets", "bindings", "tabs"],
    ),
]


# ── File I/O ─────────────────────────────────────────────────────────────

def _resolve_guide_path(filename: str) -> str:
    """Find ``filename`` in ``docs/`` relative to plugin root."""
    from hydra2dgpu import PLUGIN_ROOT
    c = os.path.join(PLUGIN_ROOT, "docs", filename)
    if os.path.exists(c):
        return c
    raise FileNotFoundError(f"Cannot find '{filename}' — tried: {c}")

def _resolve_doc_path(filename: str) -> str:
    """Resolve a guide filename to its absolute path under docs/."""
    return _resolve_guide_path(filename)


def _load_markdown(filename: str) -> str:
    """Read and return the raw markdown content of a guide file."""
    with open(_resolve_doc_path(filename), encoding="utf-8") as fh:
        return fh.read()


# ── Markdown → HTML (compact, dark-theme) ────────────────────────────────

def _markdown_to_html(md: str) -> Tuple[str, List[Tuple[str, str, int]]]:
    """Convert markdown to dark-themed compact HTML.

    Returns (html_body, [(label, anchor, level), ...]).
    """
    toc: List[Tuple[str, str, int]] = []
    parts: List[str] = [
        "<html><body style='font-family:sans-serif;font-size:10px;"
        "color:#e0e0e0;background:#1e1e1e;padding:6px;line-height:1.5;'>"
    ]
    in_code = False
    code_lines: List[str] = []
    in_table = False

    for line in md.split("\n"):
        # Code block
        if line.startswith("```"):
            if in_code:
                parts.append(
                    "<pre style='background:#2d2d2d;padding:6px;border-radius:4px;"
                    "font-size:9px;overflow-x:auto;'>"
                    + "\n".join(code_lines) + "</pre>"
                )
                code_lines = []
                in_code = False
            else:
                in_code = True
            continue
        if in_code:
            code_lines.append(line.replace("<", "&lt;").replace(">", "&gt;"))
            continue

        s = line.strip()
        if not s:
            parts.append("<p style='margin:4px 0;'>&nbsp;</p>")
            continue

        # Headers
        hm = re.match(r"^(#{1,4})\s+(.+)$", s)
        if hm:
            level = len(hm.group(1))
            text = hm.group(2)
            anchor = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
            sizes = {1: 14, 2: 12, 3: 11, 4: 10}
            colors = {1: "#4fc3f7", 2: "#81c784", 3: "#ffb74d", 4: "#e0e0e0"}
            mt = {1: 12, 2: 10, 3: 8, 4: 4}
            parts.append(
                f"<h{level} id='{anchor}' style='color:{colors[level]};"
                f"font-size:{sizes[level]}px;margin:{mt[level]}px 0 4px 0;'>"
                f"{_esc(text)}</h{level}>"
            )
            toc.append((text, anchor, level))
            continue

        # Bullet list
        bm = re.match(r"^(\s*)[-*]\s+(.+)$", s)
        if bm:
            parts.append(
                f"<li style='margin:1px 0 1px {max(0,len(bm.group(1)))}px;'>"
                f"{_inline(bm.group(2))}</li>"
            )
            continue

        # Numbered list
        nm = re.match(r"^(\s*)\d+[.)]\s+(.+)$", s)
        if nm:
            parts.append(
                f"<li style='margin:1px 0 1px {max(0,len(nm.group(1)))}px;'>"
                f"{_inline(nm.group(2))}</li>"
            )
            continue

        # Table
        if "|" in s and s.startswith("|"):
            cells = [c.strip() for c in s.split("|")[1:-1]]
            if re.match(r"^[-|:\s]+$", s):
                continue
            if not in_table:
                parts.append("<table style='border-collapse:collapse;margin:6px 0;width:100%;font-size:9px;'>")
                in_table = True
            parts.append(
                "<tr style='border-bottom:1px solid #444;'>"
                + "".join(f"<td style='padding:2px 6px;'>{_inline(c)}</td>" for c in cells)
                + "</tr>"
            )
            continue
        if in_table:
            parts.append("</table>")
            in_table = False

        # Horizontal rule
        if re.match(r"^---+\s*$", s):
            parts.append("<hr style='border:0;border-top:1px solid #444;margin:8px 0;'>")
            continue

        # Paragraph
        parts.append(f"<p style='margin:2px 0;'>{_inline(s)}</p>")

    if in_table:
        parts.append("</table>")
    parts.append("</body></html>")
    return "\n".join(parts), toc


def _esc(text: str) -> str:
    """HTML-escape special characters in text."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _url_escape(text: str) -> str:
    """Percent-encode text for safe use in URL path components."""
    import urllib.parse
    return urllib.parse.quote(text, safe="")


def _inline(text: str) -> str:
    """Convert inline markdown (code, bold, links) to HTML within a text fragment."""
    text = _esc(text)
    text = re.sub(r"``([^`]+)``",
                  r"<code style='background:#333;padding:1px 3px;border-radius:2px;font-size:9px;'>\1</code>", text)
    text = re.sub(r"`([^`]+)`",
                  r"<code style='background:#333;padding:1px 3px;border-radius:2px;font-size:9px;'>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)",
                  r'<a href="\2" style="color:#64b5f6;">\1</a>', text)
    return text


# ── Document cache ───────────────────────────────────────────────────────

@dataclass
class _CachedDoc:
    html: str
    toc: List[Tuple[str, str, int]]
    raw: str


_doc_cache: Dict[str, _CachedDoc] = {}


def _get_doc(filename: str) -> _CachedDoc:
    """Load, render, and cache a document."""
    if filename not in _doc_cache:
        raw = _load_markdown(filename)
        html, toc = _markdown_to_html(raw)
        _doc_cache[filename] = _CachedDoc(html=html, toc=toc, raw=raw)
    return _doc_cache[filename]


# ── Index page HTML ─────────────────────────────────────────────────────

def _build_index_html(matches=None) -> str:
    """Build the home / search-results index page.

    Parameters
    ----------
    matches : Optional[Dict[str, List[_SearchHit]]]
        When provided, renders search results with linked snippets.
        When None, renders the home page guide listing.
    """
    parts = [
        "<html><body style='font-family:sans-serif;font-size:10px;"
        "color:#e0e0e0;background:#1e1e1e;padding:10px;line-height:1.6;'>"
        "<h1 style='color:#4fc3f7;font-size:16px;margin:0 0 4px 0;'>HYDRA Documentation</h1>"
        "<p style='color:#888;font-size:9px;margin:0 0 12px 0;'>"
        "Use the search bar above to search all guides simultaneously, "
        "or click a guide below to open it.</p>"
        "<hr style='border:0;border-top:1px solid #333;margin:8px 0;'>"
    ]

    if matches is not None:
        # Search-results mode
        total = sum(len(v) for v in matches.values())
        parts.append(
            f"<p style='color:#b0bec5;font-size:10px;margin:4px 0 8px 0;'>"
            f"Found <b>{total}</b> match{'es' if total != 1 else ''}:</p>"
        )
        for doc_title, hits in matches.items():
            if not hits:
                continue
            parts.append(
                f"<div style='margin:6px 0;padding:4px;background:#252526;border-radius:4px;'>"
                f"<a href='dochub://open/{_url_escape(doc_title)}' style='color:#81c784;font-size:11px;text-decoration:none;'>"
                f"<b>{doc_title}</b></a>"
            )
            for hit in hits[:5]:
                anchor_str = f"#{hit.anchor}" if hit.anchor else ""
                parts.append(
                    f"<div style='color:#b0bec5;font-size:9px;padding:1px 4px;'>"
                    f"<a href='dochub://open/{_url_escape(doc_title)}{anchor_str}' "
                    f"style='color:#b0bec5;text-decoration:none;display:block;'>"
                    f"…{_esc(hit.snippet)}…</a></div>"
                )
            if len(hits) > 5:
                parts.append(f"<div style='color:#555;font-size:8px;padding:1px 4px;'>+{len(hits)-5} more</div>")
            parts.append("</div>")
        parts.append(
            "<p style='margin-top:12px;'><a href='dochub://home' "
            "style='color:#64b5f6;font-size:10px;'>← Back to all guides</a></p>"
        )
    else:
        # Home mode — list all docs
        for entry in AVAILABLE_DOCS:
            if entry.filename:
                cached = _get_doc(entry.filename)
                h1_count = sum(1 for _, _, lv in cached.toc if lv == 1)
                details = f"{h1_count} sections | {len(cached.toc)} total headings"
            else:
                details = "External documentation (opens in browser)"
            parts.append(
                f"<div style='margin:8px 0;padding:6px;background:#252526;border-radius:4px;'>"
                f"<a href='dochub://open/{_url_escape(entry.title)}' "
                f"style='color:#81c784;font-size:12px;text-decoration:none;'><b>{entry.title}</b></a>"
                f"<p style='color:#b0bec5;font-size:9px;margin:2px 0 0 0;'>{entry.description}</p>"
                f"<p style='color:#555;font-size:8px;margin:2px 0 0 0;'>{details}</p></div>"
            )

    parts.append("</body></html>")
    return "\n".join(parts)


def _entry_by_title(title: str) -> Optional[DocEntry]:
    """Look up a DocEntry by its title string."""
    for e in AVAILABLE_DOCS:
        if e.title == title:
            return e
    return None


# ── Cross-document search ───────────────────────────────────────────────

@dataclass
class _SearchHit:
    snippet: str
    anchor: str


def _search_all_docs(query: str) -> Dict[str, List[_SearchHit]]:
    """Search *query* (lower-cased) across every indexed document.

    Returns ``{doc_title: [_SearchHit, ...]}`` where each hit includes
    a text snippet and the nearest section anchor for linking.
    Sorted by match count descending.
    """
    results: Dict[str, List[_SearchHit]] = {}
    q = query.lower()
    for entry in AVAILABLE_DOCS:
        if not entry.filename:
            continue
        cached = _get_doc(entry.filename)
        hits: List[_SearchHit] = []
        nearest_anchor = ""
        for line in cached.raw.split("\n"):
            # Track current section heading for anchor
            hm = re.match(r"^#{1,4}\s+(.+)$", line)
            if hm:
                h_text = hm.group(1)
                nearest_anchor = re.sub(r"[^a-zA-Z0-9]+", "-", h_text.lower()).strip("-")
            # Check for match
            if q in line.lower():
                s = line.strip()[:120]
                hits.append(_SearchHit(snippet=s, anchor=nearest_anchor))
        if hits:
            results[entry.title] = hits[:20]
    return dict(sorted(results.items(), key=lambda kv: -len(kv[1])))


# ── DocHubWidget ────────────────────────────────────────────────────────

class DocHubWidget(QWidget):
    """Single-tab documentation hub with cross-document search.

    Page 0 — Index: home page listing all docs + search results.
    Page 1 — Viewer: full document with TOC and per-doc search.
    """

    def __init__(self, parent: Optional[QWidget] = None):
        super().__init__(parent)
        self._current_doc: Optional[str] = None
        self._toc_entries: List[Tuple[str, str, int]] = []
        self._search_results_mode = False
        self._setup_ui()

    # ── build UI ──────────────────────────────────────────────────────

    def _setup_ui(self) -> None:
        """Build the widget layout: navigation bar, stacked index/viewer pages, and TOC."""
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        # ── Top bar: nav + search ──
        top = QWidget()
        top_layout = QHBoxLayout(top)
        top_layout.setContentsMargins(6, 4, 6, 4)
        top_layout.setSpacing(4)

        self._home_btn = QPushButton("← Home")
        self._home_btn.setFlat(True)
        self._home_btn.setStyleSheet(
            "QPushButton { color: #64b5f6; font-size: 10px; border: none; padding: 2px 6px; }"
            "QPushButton:hover { color: #90caf9; }"
        )
        self._home_btn.clicked.connect(self._show_index)
        self._home_btn.setVisible(False)
        top_layout.addWidget(self._home_btn)

        top_layout.addWidget(QLabel("  Search:"))
        self._search = QLineEdit()
        self._search.setPlaceholderText("Search all guides…")
        self._search.setStyleSheet(
            "QLineEdit { background:#3c3c3c; color:#e0e0e0; border:1px solid #555; "
            "border-radius:3px; padding:2px 6px; font-size:10px; }"
        )
        self._search.textChanged.connect(self._on_search)
        top_layout.addWidget(self._search, 1)
        layout.addWidget(top)

        # ── Stacked pages ──
        self._stack = QStackedLayout()
        layout.addLayout(self._stack, 1)

        # Page 0 — Index browser
        self._index_browser = QTextBrowser()
        self._index_browser.setOpenExternalLinks(False)
        self._index_browser.setStyleSheet(
            "QTextBrowser { background:#1e1e1e; color:#e0e0e0; border:none; font-size:10px; padding:4px; }"
        )
        self._index_browser.anchorClicked.connect(self._on_index_anchor)
        self._stack.addWidget(self._index_browser)  # page 0

        # Page 1 — Doc viewer
        self._viewer_page = QWidget()
        viewer_layout = QVBoxLayout(self._viewer_page)
        viewer_layout.setContentsMargins(0, 0, 0, 0)
        viewer_layout.setSpacing(0)

        # TOC toggle
        self._toc_toggle = QPushButton("▾ Table of Contents")
        self._toc_toggle.setFlat(True)
        self._toc_toggle.setStyleSheet(
            "QPushButton { color:#81c784; font-size:11px; border:none; text-align:left; padding:4px 6px; }"
            "QPushButton:hover { color:#a5d6a7; }"
        )
        self._toc_toggle.clicked.connect(self._toggle_toc)
        viewer_layout.addWidget(self._toc_toggle)

        self._toc_list = QListWidget()
        self._toc_list.setStyleSheet(
            "QListWidget { background:#252526; border:none; border-bottom:1px solid #333; font-size:10px; }"
            "QListWidget::item { padding:2px 6px; color:#b0bec5; }"
            "QListWidget::item:hover { background:#333; color:#fff; }"
            "QListWidget::item:selected { background:#2a5f7a; color:#fff; }"
        )
        self._toc_list.setMaximumHeight(0)
        self._toc_list.itemClicked.connect(self._on_toc_click)
        viewer_layout.addWidget(self._toc_list)
        self._toc_expanded = False

        # Title label
        self._doc_title_label = QLabel()
        self._doc_title_label.setStyleSheet(
            "color:#4fc3f7; font-size:12px; font-weight:bold; padding:4px 6px 0 6px;"
        )
        viewer_layout.addWidget(self._doc_title_label)

        self._viewer_browser = QTextBrowser()
        self._viewer_browser.setOpenExternalLinks(False)  # handle everything through _on_viewer_anchor
        self._viewer_browser.setStyleSheet(
            "QTextBrowser { background:#1e1e1e; color:#e0e0e0; border:none; font-size:10px; padding:4px; }"
        )
        self._viewer_browser.anchorClicked.connect(self._on_viewer_anchor)
        viewer_layout.addWidget(self._viewer_browser, 1)

        self._stack.addWidget(self._viewer_page)  # page 1

        # ── Start on index page ──
        self._show_index()

    # ── Navigation ────────────────────────────────────────────────────

    def _show_index(self) -> None:
        """Switch to the home page showing all available documentation guides."""
        self._current_doc = None
        self._search_results_mode = False
        self._home_btn.setVisible(False)
        self._stack.setCurrentIndex(0)
        self._index_browser.setHtml(_build_index_html(matches=None))
        self._search.setPlaceholderText("Search all guides…")
        self._search.setText("")

    def _open_doc(self, title: str, anchor: str = "") -> None:
        """Open a document by title, optionally scrolling to an anchor."""
        entry = _entry_by_title(title)
        if entry is None:
            return

        # External docs (e.g. C++ API Doxygen) — open in browser
        if not entry.filename:
            import webbrowser
            from hydra2dgpu import PLUGIN_ROOT
            try:
                doxy_dir = os.path.join(PLUGIN_ROOT, "docs", "cpp", "api")
                doxy_path = os.path.join(doxy_dir, "index.html")
                if os.path.exists(doxy_path):
                    webbrowser.open(f"file://{doxy_path}")
                else:
                    self._search.setText(
                        "[C++ API docs not found — run 'cd docs && doxygen Doxyfile' to generate]"
                    )
                    self._search.selectAll()
            except Exception as _dex:
                import logging
                logging.getLogger(__name__).warning(
                    "Failed to open C++ API docs: %s", _dex, exc_info=True
                )
                self._search.setText(f"[Cannot open C++ API docs: {_dex}]")
                self._search.selectAll()
            return

        self._current_doc = title
        cached = _get_doc(entry.filename)
        self._toc_entries = cached.toc
        self._home_btn.setVisible(True)
        self._doc_title_label.setText(f"<a href='dochub://home' style='color:#4fc3f7;text-decoration:none;'>"
                                      f"◀</a>  {entry.title}")
        self._viewer_browser.setHtml(cached.html)

        # Scroll to anchor if specified
        if anchor:
            self._viewer_browser.scrollToAnchor(anchor)

        # Rebuild TOC
        self._toc_list.clear()
        seen: Dict[str, int] = {}
        for label, anchor, level in self._toc_entries:
            indent = "  " * (level - 1)
            unique_key = anchor
            count = seen.get(anchor, 0)
            seen[anchor] = count + 1
            if count > 0:
                unique_key = f"{anchor}-{count}"
            item = QListWidgetItem(f"{indent}{label}")
            item.setData(Qt.UserRole, unique_key)
            self._toc_list.addItem(item)
        self._toc_list.setMaximumHeight(0)
        self._toc_list.hide()
        self._toc_expanded = False
        self._toc_toggle.setText("▾ Table of Contents")

        self._stack.setCurrentIndex(1)
        self._search.setPlaceholderText(f"Search {entry.title}…")
        self._search.setText("")

    def _show_search_results(self, query: str) -> None:
        """Display cross-document search results on the index page."""
        matches = _search_all_docs(query)
        self._search_results_mode = True
        self._home_btn.setVisible(True)
        self._stack.setCurrentIndex(0)
        self._index_browser.setHtml(_build_index_html(matches=matches))

    # ── Search ────────────────────────────────────────────────────────

    def _on_search(self, text: str) -> None:
        """Handle search text changes: cross-doc search on index or find-in-page in viewer."""
        if not text.strip():
            self._show_index()
            return
        if self._current_doc is not None:
            # Per-doc search in viewer
            self._viewer_browser.moveCursor(QTextCursor.MoveOperation.Start)
            found = self._viewer_browser.find(text)
            if not found:
                self._viewer_browser.moveCursor(QTextCursor.MoveOperation.Start)
                self._viewer_browser.find(text)
        else:
            # Cross-doc search
            self._show_search_results(text)

    # ── Anchor clicks ─────────────────────────────────────────────────

    def _on_index_anchor(self, url: QUrl) -> None:
        """Handle anchor clicks on the index page: dochub:// commands or external URLs."""
        scheme = url.scheme()
        if scheme == "dochub":
            cmd = url.host()
            if cmd == "open":
                title = url.path().lstrip("/")
                anchor = url.fragment() or ""
                self._open_doc(title, anchor=anchor)
            elif cmd == "home":
                self._show_index()
        else:
            import webbrowser
            webbrowser.open(url.toString())

    def _on_viewer_anchor(self, url: QUrl) -> None:
        """Handle anchor clicks in the viewer: internal fragments, dochub://, or external URLs."""
        scheme = url.scheme()
        if scheme == "dochub":
            self._on_index_anchor(url)
        elif url.hasFragment() and not scheme:
            # Internal fragment — scroll to anchor
            self._viewer_browser.scrollToAnchor(url.fragment())
        elif scheme in ("http", "https", "mailto"):
            import webbrowser
            webbrowser.open(url.toString())
        elif url.hasFragment():
            self._viewer_browser.scrollToAnchor(url.fragment())

    # ── TOC toggle ────────────────────────────────────────────────────

    def _toggle_toc(self) -> None:
        """Expand or collapse the table of contents panel in the viewer."""
        if self._toc_expanded:
            self._toc_list.setMaximumHeight(0)
            self._toc_list.hide()
            self._toc_toggle.setText("▾ Table of Contents")
        else:
            max_h = min(len(self._toc_entries) * 22 + 10, 300)
            self._toc_list.setMaximumHeight(max_h)
            self._toc_list.show()
            self._toc_toggle.setText("▲ Table of Contents")
        self._toc_expanded = not self._toc_expanded

    def _on_toc_click(self, item: QListWidgetItem) -> None:
        """Scroll the viewer to the anchor corresponding to the clicked TOC entry."""
        anchor = item.data(Qt.UserRole)
        self._viewer_browser.scrollToAnchor(anchor)
