"""Multi-physics extension models for SWE2D."""

from swe2d.extensions.extension_models import (
    BedFrictionModel,
    CouplingDiagnostics,
    DrainageCouplingEngine,
    DrainageLink,
    DrainageNode,
    DrainageSolverMode,
    GodunovSolverMode,
    HydraulicStructure,
    HydraulicStructureConfig,
    HydraulicStructureEngine,
    InletExchange,
    InletType,
    NodeInletAssignment,
    OutfallExchange,
    PipeEndExchange,
    PipeNetworkConfig,
    PipeNetworkState,
    RainFieldConfig,
    RainSourceTermState,
    SWE2DEquationSet,
    SolverModelOptions,
    SpatialDiscretization,
    StructureType,
    TemporalScheme,
    TurbulenceModel,
    circular_area_from_diameter,
    circular_wet_perimeter_full,
    equivalent_circular_diameter_from_area,
)
from swe2d.extensions.drainage_network import SWE2DUrbanDrainageModule
from swe2d.extensions.structures import SWE2DStructureModule

__all__ = [
    "BedFrictionModel",
    "CouplingDiagnostics",
    "DrainageCouplingEngine",
    "DrainageLink",
    "DrainageNode",
    "DrainageSolverMode",
    "GodunovSolverMode",
    "HydraulicStructure",
    "HydraulicStructureConfig",
    "HydraulicStructureEngine",
    "InletExchange",
    "InletType",
    "NodeInletAssignment",
    "OutfallExchange",
    "PipeEndExchange",
    "PipeNetworkConfig",
    "PipeNetworkState",
    "RainFieldConfig",
    "RainSourceTermState",
    "SWE2DEquationSet",
    "SWE2DStructureModule",
    "SWE2DUrbanDrainageModule",
    "SolverModelOptions",
    "SpatialDiscretization",
    "StructureType",
    "TemporalScheme",
    "TurbulenceModel",
    "circular_area_from_diameter",
    "circular_wet_perimeter_full",
    "equivalent_circular_diameter_from_area",
]
